### ISSUE TITLE
'Ruins' leaks resources

### ISSUE THREAD

**Issue by catfact** [tyleretters/dronecaster#39]
in PR #37 , the `Routine` created in `_meta_Ruins.scd` is never halted or freed.

the supercollider interpreter environment on norns is not reset between scripts or engine changes. (we like it that way for a couple reasons; e.g. it allows well-behaved scripts/engines to acheive aural continuity.)

therefore it is very important that engines clean up *all* their allocated resources in their `cleanup` method. this does not just mean `scsynth` resources like buffers, groups etc, but also `sclang` objects that you've created at the top-level scope, or which outlive their scope. (this Routine is both.)

to illustrate the issue, ive created this branch, and added a seed value and a counter to the routine:
https://github.com/catfact/dronecaster/blob/test-leaked-routine/engine/drones/_meta_Ruins.scd#L129-L138

this exposes the issue in the REPL output: every time the `dronecaster` script is launched, _a new instance of the Routine is constructed_, which will never be halted or freed until norns undergoes a restart/shutdown. that's not great (yes, in itself the routine does not use a lot of resources, but we dont want an unbounded number of them anyway, and actually OSC traffic bandwidth is a system bottleneck.)

@ambv  you have a couple options for fixing this:

- combine all this stuff into one synthdef. it is doable. `Demand` is your friend.
- figure out a mechanism by which your Routine and whatever else in this category is registered with the engine class when your drone starts, so it can be cleaned up when the script is cleared.

**Comment by ambv** [comment]
Sorry, Ruins is my first ever work with SuperCollider and Norns. I was unaware Norns doesn't reset the SC server between scripts.

It's not clear to me how the entire drone could be rewritten into a single synthdef, and I'm afraid readability would suffer either way. However, I was contacted by @sixolet anyway to refactor Ruins (and metadrones in general) to allow better resource control. I guess I have no choice now but to prioritize this 🤓 So, option 2 of your suggestions is what I'll be pursuing.

**Comment by schollz** [comment]
thanks @catfact  sorry I hastily merged the pr.

@ambv happy to help as well. definitely Demand here is useful, checkout Eno for an example how to use Demand with chord changes. I'm happy to help as well to fit this more into the canonical dronecaster drone

**Comment by ryanlaws** [comment]
Thank you for spotting this and for the writeup @catfact 

@schollz and @ambv I appreciate your efforts and from my perspective there are no bad vibes here, we are all learning.

**Comment by ambv** [comment]
@schollz, thanks for your offer. I'll have a PR we can discuss in a day or two. Using Routines presents a new opportunity for sequencing within Dronecaster. I'll work on trying to save it but without leaking resources.

**Comment by sixolet** [comment]
@ambv I have some time this-evening-california-time if you want to collab; I feel like we could get this done in an hour or so.

**Comment by catfact** [comment]
yeah it should be quite easy to add structure to dronecaster engine by which you can register routines/whatever to be stopped at engine cleaup.

there are poblems with that. should there just be a single routine for everyone, and drone scripts may overwrite things like tick function and period? should a drone's extra sclang cruft be cleaned up when the drone changes? (b/c otherwise it becomes impossible to predict resource footprint - what if every single drone script fired of their own worker threads? then we would maybe have 50 of these things going at once)

wait a sec, does dronecaster really need sequencing? i though the thing was an exercise in radical restraint? perhaps an oppurtiunity to explore the limits of what can be done with only UGen vocabulary? (lots and lots and lots)

**Comment by ambv** [comment]
@catfact, my intention wasn't ever to degrade anyone's experience, and once you identified the resource leak, I'm eager to fix the problem. Ideally not by removing Ruins from the roster.

---

> yeah it should be quite easy to add structure to dronecaster engine by which you can register routines/whatever to be stopped at engine cleanup.

That's what I intend to do.

> there are poblems with that.

The problems you're listing are design questions which we will answer with the upcoming PR.

> what if every single drone script fired of their own worker threads? then we would maybe have 50 of these things going at once

This won't be an issue in practice as contributions to dronecaster are gated through PRs. Like, currently you only have one rogue drone, and that's due to my lack of experience in the matter 🤓 But even so, we'll make it so that changing the drone triggers resource cleanup. 

> wait a sec, does dronecaster really need sequencing?

For more complex drones which can go on for tens of minutes without sounding repetitive, sequencing will definitely be helpful. You can already hear that in Ruins, although it is but a simple example.

> i thought the thing was an exercise in radical restraint?

I don't see this being spelled out anywhere. I mean, clearly the point is for drone definitions to be straightforward but my understanding was that this is rather "radical implementation convenience" and not "radical restraint".

---

> @ambv I have some time this-evening-california-time if you want to collab; I feel like we could get this done in an hour or so.

Thanks, @sixolet. Unfortunately, I'm in Poland so evening PST is night for me. I can't do tonight but if you drop me an e-mail to lukasz@langa.pl with a few times you could connect, I'll choose one. I will work on the PR with the fix tomorrow morning my time anyway so I should have something ready for you to look at.

**Comment by sixolet** [comment]
> For more complex drones which can go on for tens of minutes without sounding repetitive, sequencing will definitely be helpful. You can already hear that in Ruins, although it is but a simple example.

This is where demand-rate ugens shine. Having now read it in detail, and listened to Ezra, and Zack in their commentary, I think converting it to use demand-rate ugens for sequencing would not be that difficult and would be a better option than changing dronecaster to use Routines for sequencing. Here's what you have in terms of sequencing:

* Random choices throughout. You will want to use https://depts.washington.edu/dxscdoc/Help/Classes/Drand.html
* Waiting a random time, but with a tempo.
  * For a probably-good-enough version of this, consider having a Drand of `[1, 1, 2, 4, 8, 16].reciprocal` (or whatnot) feeding `Impulse.kr`. 
  * For an exact version of it, consider having a https://doc.sccode.org/Classes/Stepper.html fed by a constant impulse, with its max fed by your Drand, and triggering events on the stepper output equalling zero.
* Picking a random voice. This can be accomplished by another Drand to get a random voice number. The voice parameters can each be chosen by a Select.kr()
* Your voices won't be different synthdefs anymore, they'll be fewer in number, and probably allocated round-robin by a Select.kr(), and each take all the parameters they need to form their sound, since they all have the same architecture.

> i thought the thing was an exercise in radical restraint?

I have been enjoying the radical restraint combined with the abundance of "what can we do in a synthdef". 

... separately: One of my current projects is to write a script inspired by Dronecaster with more advanced sequencing and transition capabilities, which I'm aiming to enable hosting whole "tracks" and "albums" with durations and everything.

**Comment by ambv** [comment]
Sounds like there's consensus between you three to remove the Routine capability. Fair enough, as long as we can convert Ruins to use it, I'm happy to learn how that could work. From what @sixolet writes above, this essentially sounds like a rewrite to me. I'll have a go at this tomorrow.
